MOCK_USERS = {
    "1": {
        "id": "1",
        "name": "Alice Johnson",
        "email": "alice.johnson@example.com",
        "phone": "123-456-7890",
        "channels": ["email", "push_notification"],
        "subscribed": ["sports", "films"],
    },
    "2": {
        "id": "2",
        "name": "Bob Smith",
        "email": "bob.smith@example.com",
        "phone": "234-567-8901",
        "channels": ["sms"],
        "subscribed": ["sports"],
    },
    "3": {
        "id": "3",
        "name": "Charlie Brown",
        "email": "charlie.brown@example.com",
        "phone": "345-678-9012",
        "channels": ["email", "sms", "push_notification"],
        "subscribed": ["sports", "finance"],
    },
    "4": {
        "id": "4",
        "name": "Diana Prince",
        "email": "diana.prince@example.com",
        "phone": "456-789-0123",
        "channels": ["push_notification"],
        "subscribed": ["films"],
    },
    "5": {
        "id": "5",
        "name": "John Doe",
        "email": "johndoe@example.com",
        "phone": "123456789",
        "channels": ["email"],
        "subscribed": ["finance"],
    },
}
